-- Run this once in Snowflake before running the pipeline
-- Creates the three raw landing tables

USE DATABASE BGG_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS BGG_GAMES (
    GAME_ID           VARCHAR(20),
    NAME              VARCHAR(500),
    YEAR_PUBLISHED    INTEGER,
    MIN_PLAYERS       INTEGER,
    MAX_PLAYERS       INTEGER,
    MIN_PLAYTIME      INTEGER,
    MAX_PLAYTIME      INTEGER,
    AVG_RATING        FLOAT,
    BAYES_RATING      FLOAT,
    NUM_RATINGS       INTEGER,
    COMPLEXITY_WEIGHT FLOAT,
    BGG_RANK          INTEGER,
    _LOADED_AT        TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS BGG_CATEGORIES (
    GAME_ID    VARCHAR(20),
    CATEGORY   VARCHAR(200),
    _LOADED_AT TIMESTAMP_TZ
);

CREATE TABLE IF NOT EXISTS BGG_MECHANICS (
    GAME_ID    VARCHAR(20),
    MECHANIC   VARCHAR(200),
    _LOADED_AT TIMESTAMP_TZ
);
